# 기본 이미지 설정
FROM node:lts-alpine AS builder

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 설치
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# 소스 코드 복사
COPY . .

# 빌드
RUN yarn build

# 최종 이미지 설정
FROM nginx:stable-alpine


# 빌드된 애플리케이션 파일 복사
COPY --from=builder /app/build /usr/share/nginx/html

 # Nginx 실행
CMD ["nginx", "-g", "daemon off;"]
