# Nginx 이미지를 기반으로 함
FROM nginx:latest

# Nginx 설정 파일 복사
COPY nginx.conf /etc/nginx/nginx.conf

# SSL 인증서와 키 파일 복사
# 호스트의 인증서 위치에서 컨테이너의 Nginx가 사용할 위치로 복사
COPY /etc/letsencrypt/live/j10c102.p.ssafy.io/fullchain.pem /etc/ssl/certs/fullchain.pem
COPY /etc/letsencrypt/live/j10c102.p.ssafy.io/privkey.pem /etc/ssl/private/privkey.pem