spring:
  datasource:
    url: jdbc:mysql://j10C102.p.ssafy.io:3306/fullerting
    username: fulldba
    password: full202403110344

  data:
    redis:
      host: j10C102.p.ssafy.io
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 648265936949-kqbendno25msh4hklurcvtpkvem8jkpe.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://j10c102.p.ssafy.io/login/oauth2/code/google
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile, email



  jwt:
    access: whatwehavetowantinalifeismentalsatisfactionnotmaterialone
    refresh: youforgetthisyoualwaysfeelfailevenifyouwillgeteverything
    accesstime: 36000000  # 1H -> 0하나 더 붙임...
    refreshtime: 604800000 # 7Days

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB

  jpa:
    show-sql: false  # jpa 쿼리문 출력 설정
    properties:
      hibernate:
        format_sql: true
    open-in-view: true  # SSE 설정시 필요 -> DB Connection 닫아서 connection 고갈 방지


cloud:
  aws:
    credentials:
      access-key: AKIAW3MEAWFWGVMIB3VX
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: fullerting-s3-v2
      stack:
        auto: false

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html


logging:
  level:
    org:
      springframework:
        security:
          web:
          FilterChainProxy: DEBUG


fcm:
  service-account-file: key/fullerting-fcm-firebase-adminsdk-rjmjj-0e19a90e90.json
  topic-name: alarm
  project-id: fullerting-fcm

#      hibernate:
#        type:
#          descriptor:
#            sql: trace


server:
  port: 8080
  servlet:
    context-path: /
  websocket:
    port: 9090